#!/usr/bin/env bash
# requires urxvt, slop, xdotool and wmctrl.

# vars


artist="$(mpc -f '%albumartist%' | head -1)"
song="$(mpc -f '%title%' | head -1)"
progress="$(mpc | sed 's/.*(//;s/)//;2q;d')"


# Action


	if [ "$(mpc current)" ] ; then
		echo "$a2$padding  $artist  $padding$bg"
	else
		:
	fi
