#!/bin/sh

#used = free | grep Mem | awk '{print $3/$2 * 100.0}' | awk '{print int($1+0.5)}'
#free = free | grep Mem | awk '{print $4/$2 * 100.0}' | awk '{print int($1+0.5)}'

free | grep Mem | awk '{print $3/$2 * 100.0}' | awk '{print int($1+0.5)}'